export const USER_SIGNUP = "USER_SIGNUP"
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR"
export const USER_SIGNUP_ERROR_CLEAR = "USER_SIGNUP_ERROR_CLEAR"
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"
export const USER_LOGIN_ERROR_CLEAR = "USER_LOGIN_ERROR_CLEAR"

